context:
  policy: |
    Policy Proposal: Affordable and Workforce Housing Development in Kendall Square

    Objective:
    To develop affordable and workforce housing units within Kendall Square to accommodate the needs of diverse residents, including low- to middle-income families, local employees, and students, while maintaining the area’s vibrant, innovative character.

    Background:
    Kendall Square is known for its concentration of technology firms, research institutions, and thriving startups. However, the rising cost of living has made it challenging for middle- and low-income residents to live near where they work, study, or contribute to the local economy. This policy aims to address housing affordability to sustain a diverse community and support the economic vitality of Kendall Square.

    Key Components of the Policy:

    Affordable Housing Allocation

    Goal: 30% of all new residential developments in Kendall Square must be designated as affordable housing, accessible to households earning 60-80% of the Area Median Income (AMI).
    Funding: Developers will be required to contribute to an Affordable Housing Fund managed by the city to support this goal or provide in-kind units within their developments.
    Workforce Housing Incentives

    Eligibility: Workforce housing units will target households earning between 80-120% of the AMI.
    Incentives for Developers: Tax credits and zoning flexibility will be provided to developers who designate at least 20% of units for workforce housing.
    Priority for Local Workers: Workforce housing will prioritize applicants who work within Kendall Square, such as employees of nearby research institutions, retail staff, educators, and healthcare workers.
    Community Benefits and Services

    Public Amenities: Developments must include or contribute to public spaces such as parks, community centers, or recreational facilities that benefit both residents and the broader Kendall Square community.
    Supportive Services: Partnerships with local nonprofits and organizations will provide resources such as financial counseling, tenant support, and affordable childcare for residents in affordable and workforce housing units.
    Sustainable and Transit-Oriented Development

    Green Building Standards: All new developments will meet LEED Silver certification or higher to promote environmental sustainability.
    Transit Accessibility: Developers must prioritize housing within walking distance of public transit hubs and include dedicated bike parking to encourage sustainable commuting.
    Community Engagement and Accountability

    Quarterly Reporting: Developers must report quarterly on the progress of affordable housing and workforce unit allocations.
    Community Feedback: A community advisory committee will be formed to provide ongoing feedback on the policy’s impact and address resident concerns related to housing developments.
    Annual Review: The city will review the policy annually to assess its effectiveness and make adjustments based on community feedback, housing market conditions, and changes in AMI levels.

agents:
  government:
    name: "Government Representative"
    department_name: "NA"
    instruction: |
      You need to decide whether the updated proposal from the developer should be approved or not based on the conversation history betwwen developer and community members.

  developer:
    name: "Real Estate Developer"
    development_proposal: |
      We plan to build a huge apartment. The detailed plan includes:
      
      Project Location and Scope
      The apartment complex will be located in Downtown Edge District, approximately 2 miles from the city center and adjacent to a new transit corridor.
      The complex will span 10 acres, with 4 buildings each consisting of 12 floors, accommodating approximately 500 residential units. The units will vary in size: 200 studios, 150 one-bedrooms, 100 two-bedrooms, and 50 three-bedrooms.
      
      Design and Architecture
      The buildings will have a contemporary architectural style with energy-efficient glass façades and green building materials.
      Smart home technology, including automated lighting, temperature control, and security systems, will be standard in each unit to enhance comfort and sustainability.
      A 1-acre communal park with landscaped gardens, a playground, and walking paths will serve as the central recreational space for residents.
      
      Community Amenities
      The complex will feature a 24/7 fitness center, a rooftop garden on each building, a coworking space for remote professionals, and a communal lounge and event hall for residents.
      5,000 square feet of retail space on the ground floor will include a grocery store, a coffee shop, and essential services, creating a mini-neighborhood within the complex.
      
      Transportation and Accessibility
      Designed for eco-friendly commuting, the complex will have bicycle storage areas and dedicated bike lanes connecting to nearby paths.
      300 parking spaces will be available for residents, including 50 spaces with electric vehicle (EV) charging stations.
      A free shuttle service will connect the complex to the central metro station, running every 30 minutes during peak hours.
      
      Environmental Considerations
      The buildings will incorporate solar panels on the rooftops, designed to generate 20% of the complex's total energy requirements.
      Rainwater harvesting and greywater recycling systems will reduce water consumption by an estimated 30%, contributing to sustainability.
      The complex will pursue LEED Gold Certification, adhering to strict environmental standards.
      
      Budget and Funding
      The estimated project budget is $120 million, with $60 million from private investors, $40 million through bank financing, and $20 million from government incentives for green construction.
      
      Timeline and Phases
      Phase 1 (site preparation and foundational work) will begin in March 2025.
      Phase 2 (structural development) will start in September 2025 and conclude by December 2026.
      Phase 3 (interiors, amenities, and landscaping) will commence in January 2027, with the full project completion and resident move-in expected by September 2027.

  citizens:
    citizen1:
      name: "citizen1"
      role: "Member"
      instruction: |
        You are a Community Member affected by the development. Your key actions:
        1. Express specific concerns (traffic, noise, environment, etc.)
        2. Share personal impacts
        3. Ask questions about the project
        4. Suggest reasonable alternatives
        5. Represent community interests

    citizen2:
      name: "citizen2"
      role: "Community Member"
      instruction: |
        You are a Community Member with vested interest in the project outcome. Your key actions:
        1. Highlight potential issues (property values, public spaces, safety, etc.)
        2. Describe how the development could impact your quality of life
        3. Seek clarifications about long-term impacts
        4. Offer constructive feedback and ideas
        5. Advocate for community well-being

conclusion:
  rule: |
    At the conclusion of the hearing, the Government Representative will evaluate the proposal based on the following criteria to determine whether to approve or deny the policy:

    Approval Criteria:
      1. Public Interest Alignment: The proposal must align with the long-term interests of the community, considering economic, environmental, and social impacts.
      2. Mitigation of Negative Impacts: The developer has provided feasible solutions to mitigate significant negative impacts (e.g., traffic, noise, environmental concerns) raised by the community members.
      3. Community Benefits: The project offers clear and measurable benefits to the community, such as improved infrastructure, job creation, or enhanced public spaces.
      4. Regulatory Compliance: The proposal complies with all relevant regulations and zoning laws, and there are no legal barriers to its implementation.
      5. Commitment to Accountability: The developer demonstrates a clear plan for ongoing accountability, including mechanisms for addressing community concerns post-implementation.

    Denial Criteria:
      1. Significant Unresolved Community Concerns: Key issues raised by community members remain unaddressed or inadequately mitigated, posing potential risks to the community's well-being.
      2. Insufficient Public Benefit: The project does not provide enough benefit to the community to justify the associated impacts or costs.
      3. Non-Compliance with Regulations: The proposal fails to meet legal or regulatory standards, and no viable path exists to bring it into compliance.
      4. Lack of Transparency or Accountability: The developer is unable or unwilling to commit to ongoing transparency, reporting, or community engagement after project approval.
      5. Environmental or Safety Risks: The project presents unmitigated risks to public health, safety, or the local environment, making it incompatible with the community’s sustainability goals.

    Outcome:
      - Approval: If all approval criteria are met and no denial criteria apply, the Government Representative may approve the policy, documenting any conditions or follow-up actions required.
      - Conditional Approval: If some concerns remain but can be resolved through specific conditions, the Government Representative may grant conditional approval, stipulating required actions from the developer.
      - Denial: If any denial criteria are met and cannot be adequately addressed, the Government Representative should deny the policy, providing a clear explanation of the reasons and any recommendations for project modifications if resubmission is an option.