from src.prompts.prompts import \
    COMMUNITY_MEMBER_PROMPT_TEMPLATE, \
    DEVELOPER_STAGE_1_PROMPT_TEMPLATE, \
    DEVELOPER_STAGE_2_PROMPT_TEMPLATE, \
    GOVERNMENT_REPRESENTATIVE_PROMPT_TEMPLATE
